apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-cnsw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-cnsw
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-cnsw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-cnsw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-cnsw
    spec:
      containers:
      - image: quay.io/rh-gitops-bot/rhtap-demo-mfcx-tenant/rhtap-demo-app/hacbs-test-project-cnsw@sha256:1d6d392c2c6da1dcafc677b4242e5ac0fdd9ee9ee176b16fc4a61fc2448ff613
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
